# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Router-Statistics
version:      0.95_1
version_from: lib/Router/Statistics.pm
installdirs:  site
requires:
    Net::SNMP:                     1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
